### ISSUE TITLE
GeoLocator Issue after upgrading flutter version in to 2.5.1

### ISSUE THREAD

**Issue by INReportInsitemy** [Baseflow/flutter-geolocator#864]
## 🐛 Bug Report

C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^
  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Running Gradle task 'assembleDebug'...                              6.7s
Gradle task assembleDebug failed with exit code 1

### Expected behavior
Build and compiled
### Reproduction steps
flutter build apk --debug
### Configuration

**Version:** 7.7.0 / 7.6.2

**Platform:** 
- [ ] :iphone: iOS
- [ x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi, please make sure you set `compileSdkVersion` in your `android/app/build.gradle` file to `31` when using geolocator version 7.7.0. If you cannot support Android 12 yet make sure to pin the dependency on geolocator to version 7.6.2 (make sure you pin it and not use the caret `^` symbol).
