### ISSUE TITLE
Cannot get location with flutter web on safari

### ISSUE THREAD

**Issue by ZETA-6PO** [Baseflow/flutter-geolocator#774]
## 🐛 Bug Report

I uploaded my application to a web server, I can get the location using the Google Chrome browser on pc, but when I use Safari on a phone, it doesn't work and just charges.

### Expected behavior
Normally, it should ask permission and locate me like on chrome PC.

### Reproduction steps
1) Use the getLocation() function in your app
```import 'package:geolocator/geolocator.dart';

Future<List> getLocation() async {
  bool serviceEnabled;
  LocationPermission permission;

  // Test if location services are enabled.
  serviceEnabled = await Geolocator.isLocationServiceEnabled();
  if (!serviceEnabled) {
    // Location services are not enabled don't continue
    // accessing the position and request users of the 
    // App to enable the location services.
    return Future.error('Location services are disabled.');
  }

  permission = await Geolocator.checkPermission();
  if (permission == LocationPermission.denied) {
    permission = await Geolocator.requestPermission();
    if (permission == LocationPermission.denied) {
      // Permissions are denied, next time you could try
      // requesting permissions again (this is also where
      // Android's shouldShowRequestPermissionRationale 
      // returned true. According to Android guidelines
      // your App should show an explanatory UI now.
      return [false, 'permission refusée.'];
    }
  }
  
  if (permission == LocationPermission.deniedForever) {
    // Permissions are denied forever, handle appropriately. 
    return [false, 'permission refusée.'];
  } 

  // When we reach here, permissions are granted and we can
  // continue accessing the position of the device.
  return [true, await Geolocator.getCurrentPosition()];
}
```

2) build it for web with no sound null safety
3) upload it on firebase hosting

### Configuration

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.4.0-1.0.pre.32, on Microsoft Windows [version 10.0.19041.1052], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] VS Code (version 1.57.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Version:** 7.2.0
pubspec.yaml:
```
name: prospector
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sizer: ^2.0.13
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  file_picker: ^2.1.7
  http: ^0.12.2
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  geolocator: ^7.2.0+1

dependency_overrides:
  firebase_storage_web: ^0.1.1+3
  crypto: ^2.1.5
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Basic
      fonts:
        - asset: fonts/Basic-Regular.ttf
```

**Platform:** 
- WEB

**Comment by chrissto79** [comment]
I have the same issue.

**Comment by chrissto79** [comment]
also, the example at https://fir-test-web-geolocator-2.web.app/#/ does not work in my safari on macOS (Version 14.0.3 (16610.4.3.1.7)) and iOS.

**Comment by Rexios80** [comment]
Geolocator seems to work fine in local debug web builds, but fails to work in deployed release builds. It is a very bizarre issue.

**Comment by lazytesting** [comment]
I have a similar issue in chromium (Chrome/Brave). In debug mode the location works fine, but when I built it fails.
Tried to get some additional information on this by adding some print statements in this package and doing a profile build.

Here I added a print and an extra catch:
```
  @override
  Future<Position> getCurrentPosition({
    bool? enableHighAccuracy,
    Duration? timeout,
  }) async {
    try {
      final geoPosition = await _geolocation.getCurrentPosition(
        enableHighAccuracy: enableHighAccuracy,
        timeout: timeout,
      );
      print("position lat:");
      print(geoPosition.coords);
      return toPosition(geoPosition);
    } on html.PositionError catch (e) {
      throw convertPositionError(e);
    } on Exception catch (e) {
      print("oops");
      print(e);
      throw e;
    }
  }
```

which results in the following exception:

```
NoSuchMethodError: method not found: 'get$coords' (J.getInterceptor$x(...).get$coords is not a function)

with the following
Uncaught Exception: oops
    at Object.wrapException (http://localhost:5000/main.dart.js:7167:17)
    at http://localhost:5000/main.dart.js:110356:23
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:5000/main.dart.js:10865:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:5000/main.dart.js:54944:12)
    at _awaitOnObject_closure.call$1 (http://localhost:5000/main.dart.js:54930:32)
    at _RootZone.runUnary$2$2 (http://localhost:5000/main.dart.js:56711:18)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:5000/main.dart.js:55690:51)
    at Object._Future__propagateToListeners (http://localhost:5000/main.dart.js:11122:93)
    at _Future._completeWithValue$1 (http://localhost:5000/main.dart.js:55532:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:5000/main.dart.js:55620:18)
```

I'm still new to Dart and Flutter and this was the point where I got stuck, but maybe it helps someone else locating the issue.

**Comment by lazytesting** [comment]
after further investigation I found that it's caused by this one https://github.com/Baseflow/flutter-geolocator/issues/693.
My current workaround is to build with the --no-sound-null-safety flag

**Comment by ZETA-6PO** [comment]
I ended up making my own interop lib script for dart with the js geolocation api.

**Comment by Sammius** [comment]
Are there any suggestions on how to solve this problem?

**Comment by florissmit1** [comment]
Thanks all, for reporting your issues. We're aware of the issue and are currently working on a fix in this PR: https://github.com/Baseflow/flutter-geolocator/pull/897. It is indeed an issue caused by the Permissions API, which is not supported on Safari, as @artificerchris mentioned earlier. For now, you can bypass the issue by **not** making use of the `checkPermission()` on web. Using the `getCurrentLocation()` method for location fetching should do the job for now.

**Comment by ws6ramair** [comment]
Hi @mvanbeusekom, I noticed this was merged in 8.0.0, however I'm still seeing this error in flutter web on Safari (when using 8.0.0 and 8.0.1):

```
minified:hn
PlatformException(LOCATION_SERVICES_NOT_SUPPORTED, Location services are not supported on this browser., null, null)
```

Was the fix for this merged?

**Comment by Rexios80** [comment]
What flutter/dart version are you using?

**Comment by ws6ramair** [comment]
sorry, should have posted this earlier:

Flutter 2.2.2 and Dart 2.13.3

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/jasonnguyen/development/flutter
    • Framework revision d79295af24 (7 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jasonnguyen/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71
```

**Comment by mvanbeusekom** [comment]
Hi @ws6ramair, 

You are correct, it seems we missed on line of code that still threw the `LOCATION_SERVICES_NOT_SUPPORTED` exception when calling the `checkPermission` method. 

In light of this I did a more detailed review and refactored the code to return a `LocationPermission.unableToDetermine` status when the `Geolocator.checkPermission` method is called on a browser (for example Safari) that doesn't implement the [Permission API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API).

**Comment by ws6ramair** [comment]
Thanks so much @mvanbeusekom! These changes are perfect. Really appreciate your help.
