### ISSUE TITLE
Does not compile with flutter 2.8.1 and geolocator_android 3.0.2

### ISSUE THREAD

**Issue by pognibene** [Baseflow/flutter-geolocator#956]
## 🔙 Regression

Flutter app compilation fails with the latest geolocator_android 3.0.2/flutter geolocator 8.0.3 

### Old (and correct) behavior
Could compile and run my app, with flutter 2.5.1 and flutter_geolocator

### Current behavior

At compilation time:
/home/pascal/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-3.0.2/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
/home/pascal/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-3.0.2/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^
  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

### Reproduction steps
Create an app with flutter 2.8.1 or later, using geolocator ^8.0.3
try flutter_run
compilation fails

Tried to remove/reinstall flutter, flutter clean, empty all caches, compile on the command line or from Android Studio : does not work.

### Configuration
Linux debian x64
Flutter 2.8.1 installed manually
geolocator ^8.0.3

**Version:** 1.x

**Platform:** 
- [ x] :iphone: iOS
- [ x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi, please make sure you set `compileSdkVersion` in your `android/app/build.gradle` file to 31 when using geolocator version 7.7.0 or higher. If you cannot support Android 12 yet make sure to pin the dependency on geolocator to version 7.6.2 (in this case make sure you pin it and not use the caret ^ symbol). See also the [CHANGELOG.md](https://github.com/Baseflow/flutter-geolocator/blob/master/geolocator/CHANGELOG.md#770) and documentation in the Android section of the [README.md](https://github.com/Baseflow/flutter-geolocator/blob/master/geolocator/README.md).

**Comment by vikramsinghrajpoot** [comment]
Facing same issue with geolocator: ^9.0.2 and flutter 3.7.0.
